=== wizard88mc/GreenCMS/pagesSource/globalDetails/styleSheets.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="styleSheets" type="TStyleSheets" ></xs:element>
	
	<xs:complexType name="TStyleSheets">
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="styleSheet" type="TStyleSheet" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="TStyleSheet">
		<xs:sequence minOccurs="1" maxOccurs="1">
			<xs:element name="fileName" type="xs:string" />
			<xs:element name="media" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== wizard88mc/GreenCMS/pagesSource/globalDetails/styleSheets.xml
<?xml version="1.0" encoding="UTF-8"?>
<styleSheets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="styleSheets.xsd">
	<styleSheet>
		<fileName>base</fileName>
		<media>handheld, screen</media>
	</styleSheet>
	<styleSheet>
		<fileName>small</fileName>
		<media>handheld, screen and (max-width:480px), only screen and (max-device-width:480px)</media>
	</styleSheet>
	<styleSheet>
		<fileName>print</fileName>
		<media>print</media>
	</styleSheet>
	<styleSheet>
		<fileName>aural</fileName>
		<media>aural</media>
	</styleSheet>
</styleSheets>
