=== wizard88mc/GreenCMS/www/xml_files/databaseDefinition/ActiveNews.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="TableActiveNews" type="TTableActiveNews">
		<xs:annotation>
			<xs:documentation>Definizione della tabella ActiveNews</xs:documentation>
		</xs:annotation>
	</xs:element>
	
	<xs:complexType name="TTableActiveNews">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="ActiveNews" type="TActiveNews" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="TActiveNews">
		<xs:sequence minOccurs="1" maxOccurs="1">
			<xs:element name="ID" type="xs:integer" />
			<xs:element name="Title" type="xs:string" />
			<xs:element name="Date" type="xs:date" />
			<xs:element name="Time" type="xs:time" />
			<xs:element name="Text" type="xs:string" />
			<xs:element name="Publisher" type="xs:string" />
			<xs:element name="Type" type="xs:string" />
			<xs:element name="Archive" type="xs:string" />
			<xs:element name="ExpirationDate" type="xs:date" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== wizard88mc/GreenCMS/www/xml_files/ActiveNews.xml
<?xml version="1.0" encoding="UTF-8"?>
<TableActiveNews xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="databaseDefinition/ActiveNews.xsd" IDLastNews="28">
	
	<ActiveNews>
	<ID>28</ID>
	<Title>Incontro ERASMUS Informatica</Title>
	<Date>2012-02-14</Date>
	<Time>13:02:00</Time>
	<Text>A tutti gli studenti di Informatica interessati al programma ERASMUS.

Siete invitati a presentarvi Martedì 21 febbraio alle ore 5pm in aula riunioni al 4 piano di Torre Archimede al fine di:

1) raccogliere gli interessi degli studenti in merito alle sedi preferite, in maniera tale da evidenziare e possibilmente risolvere eventuali inefficienze (e.g. evitare che tutti si concentrino su una sede, diminuendo per molti la probabilità di successo).

2) fare un test informale di inglese (di cui si terrà eventualmente conto in fase di selezione delle domande), necessario ad evidenziare necessità di miglioramento della lingua prima della partenza.
Per Aix-Marseille il test sarà di lingua francese.

I docenti di Informatica responsabili dei flussi ERASMUS.</Text>
	<Publisher>Mauro Conti</Publisher>
	<Type>G</Type>
	<Archive>F</Archive>
	<ExpirationDate>2012-02-22</ExpirationDate></ActiveNews></TableActiveNews>
