=== wizard88mc/GreenCMS/www/xml_files/databaseDefinition/MailingListsContactsJoins.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="TableJoinsMailingListsContacts" type="TTableJoinsMailingListsContacts"/>
	
	<xs:complexType name="TTableJoinsMailingListsContacts">
		<xs:sequence minOccurs="1" maxOccurs="1">
			<xs:element name="TableJoinEventsMailingLists" type="TTableJoin" />
			<xs:element name="TableMalingLists" type="TTableMailingLists" />
			<xs:element name="TableContacts" type="TTableContacts" />
			<xs:element name="TableJoinMailingListsContacts" type="TTableJoinMailingListsContacts" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="TTableJoin">
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="JoinEventMailingList" type="TJoinEventMailingList" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="TJoinEventMailingList">
		<xs:sequence minOccurs="1" maxOccurs="1">
			<xs:element name="EventID" type="xs:integer" />
			<xs:element name="MailingListsIDs" type="TMailingListsIDs" />
			<xs:element name="AdditionalsEmails" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="TMailingListsIDs">
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="MailingListID" type="xs:integer" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="TTableMailingLists">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="MailingList" type="TMailingList" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="TMailingList">
		<xs:sequence minOccurs="1" maxOccurs="1">
			<xs:element name="ID" type="xs:integer" />
			<xs:element name="Name" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="TTableContacts">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="Contact" type="TContact" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="TContact">
		<xs:sequence minOccurs="1" maxOccurs="1">
			<xs:element name="ID" type="xs:integer" />
			<xs:element name="Name" type="xs:string" />
			<xs:element name="Surname" type="xs:string" />
			<xs:element name="Email" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="TTableJoinMailingListsContacts">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="JoinContactMailingList" type="TJoinContactMailingList" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="TJoinContactMailingList">
		<xs:sequence minOccurs="1" maxOccurs="1">
			<xs:element name="IDMailingList" type="xs:integer" />
			<xs:element name="IDContact" type="xs:integer" />
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== wizard88mc/GreenCMS/www/MailingListsContactsJoins.xml
<?xml version="1.0" encoding="UTF-8"?>
<TableJoinsMailingListsContacts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="databaseDefinition/MailingListsContactsJoins.xsd">
	<TableJoinEventsMailingLists>
		<JoinEventMailingList>
			<EventID>1</EventID>
			<MailingListsIDs/>
			<AdditionalsEmails>users@math.unipd.it</AdditionalsEmails>
		</JoinEventMailingList>
		<JoinEventMailingList>
			<EventID>2</EventID>
			<MailingListsIDs/>
			<AdditionalsEmails/>
		</JoinEventMailingList>
		
		<JoinEventMailingList>
			<EventID>3</EventID>
			<MailingListsIDs/>
			<AdditionalsEmails/>
		</JoinEventMailingList>
		
		<JoinEventMailingList>
			<EventID>4</EventID>
			<MailingListsIDs/>
			<AdditionalsEmails>gaggi@math.unipd.it, wizard88mc@gmail.com</AdditionalsEmails>
		</JoinEventMailingList>

		
		<JoinEventMailingList>
			<EventID>5</EventID>
			<MailingListsIDs><MailingListID>1</MailingListID><MailingListID>7</MailingListID></MailingListsIDs>
			<AdditionalsEmails/>
		</JoinEventMailingList>
		</TableJoinEventsMailingLists>
	<TableMailingLists>
		
		<MailingList>
		<ID>2</ID>
		<Name>Informatici Padova</Name></MailingList>
		<MailingList>
		  <ID>3</ID>
		  <Name>dottorandi</Name>
		</MailingList>
			
			<MailingList>
				<ID>4</ID>
				<Name>AggiunteStandard</Name>
			</MailingList>
			<MailingList>
				<ID>5</ID>
				<Name>verifica</Name>
			</MailingList>
			
			
			<MailingList>
				<ID>6</ID>
				<Name>Mailing prova</Name>
			</MailingList>
			<MailingList>
				<ID>7</ID>
				<Name>Users</Name>
			</MailingList></TableMailingLists>
	<TableContacts>
		<Contact>
		<ID>4</ID>
		<Name>Matteo</Name>
		<Surname>Ciman</Surname>
		<Email>mciman@studenti.math.unipd.it</Email></Contact>
		<Contact>
		<ID>5</ID>
		<Name>Ombretta</Name>
		<Surname>Gaggi</Surname>
		<Email>gaggi@math.unipd.it</Email></Contact><Contact>
		<ID>6</ID>
		<Name>Silvia</Name>
		<Surname>Crafa</Surname>
		<Email>crafa@math.unipd.it</Email></Contact><Contact>
		<ID>7</ID>
		<Name>Claudio Enrico</Name>
		<Surname>Palazzi</Surname>
		<Email>cpalazzi@math.unipd.it</Email></Contact>
	
		
		<Contact>
			<ID>8</ID>
			<Name>Alessandro</Name>
			<Surname>Sperduti</Surname>
			<Email>sperduti@math.unipd.it</Email></Contact>
		<Contact>
			<ID>9</ID>
			<Name>Gilberto</Name>
			<Surname>Fil√®</Surname>
			<Email>gilberto@math.unipd.it</Email></Contact>
		<Contact>
			<ID>10</ID>
			<Name>Fabio</Name>
			<Surname>Aiolli</Surname>
			<Email>aiolli@math.unipd.it</Email></Contact>
		<Contact>
			<ID>11</ID>
			<Name>Massimo</Name>
			<Surname>Marchiori</Surname>
			<Email>massimo@math.unipd.it</Email></Contact>
		
		<Contact>
			<ID>13</ID>
			<Name>Francesca</Name>
			<Surname>Rossi</Surname>
			<Email>frossi@math.unipd.it</Email></Contact>
		<Contact>
			<ID>14</ID>
			<Name>Francesco</Name>
			<Surname>Ranzato</Surname>
			<Email>ranzato@math.unipd.it</Email></Contact>
		<Contact>
			<ID>16</ID>
			<Name>Brent K.</Name>
			<Surname>Venable</Surname>
			<Email>kvenable@math.unipd.it</Email></Contact>
		<Contact>
			<ID>18</ID>
			<Name>Livio</Name>
			<Surname>Colussi</Surname>
			<Email>colussi@math.unipd.it</Email></Contact>
		<Contact>
			<ID>19</ID>
			<Name>Tullio</Name>
			<Surname>Vardanega</Surname>
			<Email>tullio.vardanega@math.unipd.it</Email></Contact>
		<Contact>
			<ID>21</ID>
			<Name>Paolo</Name>
			<Surname>Baldan</Surname>
			<Email>baldan@math.unipd.it</Email></Contact>
		<Contact>
			<ID>22</ID>
			<Name>Maria Emilia</Name>
			<Surname>Maietti</Surname>
			<Email>maietti@math.unipd.it</Email></Contact>
		<Contact>
			<ID>23</ID>
			<Name>Maria Silvia</Name>
			<Surname>Pini</Surname>
			<Email>mpini@math.unipd.it</Email></Contact>
		<Contact>
			<ID>24</ID>
			<Name>Susi</Name>
			<Surname>Dulli</Surname>
			<Email>dulli@math.unipd.it</Email></Contact>
		<Contact>
			<ID>25</ID>
			<Name>Giovanni</Name>
			<Surname>Da San Martino</Surname>
			<Email>dasan@math.unipd.it</Email></Contact>
		<Contact>
			<ID>26</ID>
			<Name>Sabina</Name>
			<Surname>Rossi</Surname>
			<Email>srossi@dsi.unive.it</Email></Contact>
		<Contact>
			<ID>27</ID>
			<Name>Fabio</Name>
			<Surname>Marcuzzi</Surname>
			<Email>marcuzzi@math.unipd.it</Email></Contact>
		<Contact>
			<ID>28</ID>
			<Name>Mirco</Name>
			<Surname>Gelain</Surname>
			<Email>mgelain@math.unipd.it</Email></Contact>
		<Contact>
			<ID>29</ID>
			<Name>Burattin</Name>
			<Surname>Andrea</Surname>
			<Email>burattin@math.unipd.it</Email></Contact>
		<Contact>
			<ID>30</ID>
			<Name>Alessandro</Name>
			<Surname>Maccagnan</Surname>
			<Email>maccagnan@math.unipd.it</Email></Contact>
		<Contact>
			<ID>31</ID>
			<Name>Enrico</Name>
			<Surname>Mezzetti</Surname>
			<Email>emezzett@math.unipd.it</Email></Contact>
		<Contact>
			<ID>32</ID>
			<Name>Marco</Name>
			<Surname>Panunzio</Surname>
			<Email>panunzio@math.unipd.it</Email></Contact>
		<Contact>
			<ID>33</ID>
			<Name>Lino</Name>
			<Surname>Possamai</Surname>
			<Email>possamai@math.unipd.it</Email></Contact>
		<Contact>
			<ID>34</ID>
			<Name>Augusto</Name>
			<Surname>Ferrante</Surname>
			<Email>augusto@dei.unipd.it</Email></Contact>
		<Contact>
			<ID>35</ID>
			<Name>Afferenti</Name>
			<Surname>Tutti</Surname>
			<Email>users@math.unipd.it</Email></Contact></TableContacts>
	<TableJoinMailingListsContacts>
		
		
		<JoinContactMailingList>
			<IDMailingList>2</IDMailingList>
			<IDContact>5</IDContact>
		</JoinContactMailingList>
		<JoinContactMailingList>
			<IDMailingList>2</IDMailingList>
			<IDContact>6</IDContact>
		</JoinContactMailingList>
		<JoinContactMailingList>
			<IDMailingList>2</IDMailingList>
			<IDContact>7</IDContact>
		</JoinContactMailingList>
	
		
		
		
		
		
		
		<JoinContactMailingList>
			<IDMailingList>2</IDMailingList>
			<IDContact>8</IDContact></JoinContactMailingList>
		<JoinContactMailingList>
			<IDMailingList>2</IDMailingList>
			<IDContact>9</IDContact></JoinContactMailingList>
		<JoinContactMailingList>
			<IDMailingList>2</IDMailingList>
			<IDContact>10</IDContact></JoinContactMailingList>
		<JoinContactMailingList>
			<IDMailingList>2</IDMailingList>
			<IDContact>11</IDContact></JoinContactMailingList>
		
		<JoinContactMailingList>
			<IDMailingList>3</IDMailingList>
			<IDContact>29</IDContact></JoinContactMailingList>
		<JoinContactMailingList>
			<IDMailingList>3</IDMailingList>
			<IDContact>30</IDContact></JoinContactMailingList>
		<JoinContactMailingList>
			<IDMailingList>3</IDMailingList>
			<IDContact>31</IDContact></JoinContactMailingList>
		<JoinContactMailingList>
			<IDMailingList>3</IDMailingList>
			<IDContact>32</IDContact></JoinContactMailingList>
		<JoinContactMailingList>
			<IDMailingList>3</IDMailingList>
			<IDContact>33</IDContact></JoinContactMailingList>
		<JoinContactMailingList>
			<IDMailingList>2</IDMailingList>
			<IDContact>18</IDContact></JoinContactMailingList>
		<JoinContactMailingList>
			<IDMailingList>2</IDMailingList>
			<IDContact>13</IDContact></JoinContactMailingList>
		<JoinContactMailingList>
			<IDMailingList>2</IDMailingList>
			<IDContact>14</IDContact></JoinContactMailingList>
		<JoinContactMailingList>
			<IDMailingList>2</IDMailingList>
			<IDContact>16</IDContact></JoinContactMailingList>
		<JoinContactMailingList>
			<IDMailingList>2</IDMailingList>
			<IDContact>19</IDContact></JoinContactMailingList>
		<JoinContactMailingList>
			<IDMailingList>2</IDMailingList>
			<IDContact>21</IDContact></JoinContactMailingList>
		<JoinContactMailingList>
			<IDMailingList>4</IDMailingList>
			<IDContact>22</IDContact></JoinContactMailingList>
		<JoinContactMailingList>
			<IDMailingList>4</IDMailingList>
			<IDContact>23</IDContact></JoinContactMailingList>
		<JoinContactMailingList>
			<IDMailingList>4</IDMailingList>
			<IDContact>24</IDContact></JoinContactMailingList>
		<JoinContactMailingList>
			<IDMailingList>4</IDMailingList>
			<IDContact>25</IDContact></JoinContactMailingList>
		<JoinContactMailingList>
			<IDMailingList>4</IDMailingList>
			<IDContact>26</IDContact></JoinContactMailingList>
		<JoinContactMailingList>
			<IDMailingList>4</IDMailingList>
			<IDContact>27</IDContact></JoinContactMailingList>
		<JoinContactMailingList>
			<IDMailingList>4</IDMailingList>
			<IDContact>28</IDContact></JoinContactMailingList>
		<JoinContactMailingList>
			<IDMailingList>4</IDMailingList>
			<IDContact>34</IDContact></JoinContactMailingList>
		<JoinContactMailingList>
			<IDMailingList>5</IDMailingList>
			<IDContact>4</IDContact></JoinContactMailingList>
		
		<JoinContactMailingList>
			<IDMailingList>7</IDMailingList>
			<IDContact>35</IDContact></JoinContactMailingList></TableJoinMailingListsContacts>
</TableJoinsMailingListsContacts>
