=== wizard88mc/GreenCMS/perl/coursesSite/CoursesWebsites.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="CoursesWebsites" type="TCoursesWebsites">
		<xs:annotation>
			<xs:documentation>Definizione della tabella CourseWebsite</xs:documentation>
		</xs:annotation>
	</xs:element>
	
	<xs:complexType name="TCoursesWebsites" >
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="CourseWebsite" type="TCourseWebsite" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="TCourseWebsite" >
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="Course" type="xs:string" />
			<xs:element name="LinkDescription" type="TLinkDescription" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="TLinkDescription">
		<xs:sequence minOccurs="1" maxOccurs="1">
			<xs:element name="Link" type="xs:string" />
			<xs:element name="Description" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== wizard88mc/GreenCMS/perl/coursesSite/CoursesWebsitesLaurea.xml
<?xml version="1.0" encoding="UTF-8"?>
<CoursesWebsites xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CoursesWebsites.xsd">
<CourseWebsite>
	<Course>Tecnologie web</Course>
	<LinkDescription>
		<Link>http://docenti.math.unipd.it/gaggi/tecweb</Link>
		<Description/>
	</LinkDescription>
</CourseWebsite>
<CourseWebsite>
	<Course>Basi di dati</Course>
	<LinkDescription>
		<Link>http://www.math.unipd.it/~baldan/BD</Link>
		<Description/>
	</LinkDescription>
</CourseWebsite>
<CourseWebsite>
	<Course>Architettura degli elaboratori</Course>
	<LinkDescription>
		<Link>http://www.math.unipd.it/~sperduti/architettura1.html</Link>
		<Description/>
	</LinkDescription>
</CourseWebsite>
<CourseWebsite>
	<Course>Sistemi operativi</Course>
	<LinkDescription>
		<Link>http://www.math.unipd.it/~cpalazzi/sistemioperativi.html</Link>
		<Description/>
	</LinkDescription>
</CourseWebsite>
<CourseWebsite>
	<Course>Reti e sicurezza</Course>
	<LinkDescription>
		<Link>http://corsi.math.unipd.it/reti/</Link>
		<Description/>
	</LinkDescription>
</CourseWebsite>
<CourseWebsite>
	<Course>Programmazione concorrente e distribuita</Course>
	<LinkDescription>
		<Link>http://www.math.unipd.it/~crafa/prog3/</Link>
		<Description/>
	</LinkDescription>
</CourseWebsite>
<CourseWebsite>
	<Course>Logica</Course>
	<LinkDescription>
		<Link>http://www.math.unipd.it/~maietti</Link>
		<Description/>
	</LinkDescription>
</CourseWebsite>
<CourseWebsite>
	<Course>Matematica discreta e probabilit√†</Course>
	<LinkDescription>
		<Link>http://www.math.unipd.it/~carla/docs/MatDiscrProb10-11/MatDiscrProb10-11.htm</Link>
		<Description>Sito per la parte di matematica discreta</Description>
	</LinkDescription>
</CourseWebsite>
<CourseWebsite>
	<Course>Automi e linguaggi formali</Course>
	<LinkDescription>
		<Link>http://www.math.unipd.it/~frossi/automi2010-1.html</Link>
		<Description>Sito per la parte di automi e linguaggi formali</Description>
	</LinkDescription>
</CourseWebsite>

<CourseWebsite>
	<Course>Ingegneria del Software (Mod. A)</Course>
	<LinkDescription>
		<Link>http://www.math.unipd.it/~tullio/IS-1/2010/</Link>
		<Description>Sito per la parte di Ingegneria del Software (Mod. A)</Description>
	</LinkDescription>
</CourseWebsite>

<CourseWebsite>
	<Course>Lingua inglese</Course>
	<LinkDescription>
		<Link>http://corsi.math.unipd.it/inglese/</Link>
		<Description/>
	</LinkDescription>
</CourseWebsite>


</CoursesWebsites>
